### ISSUE TITLE
Improvement - menu

### ISSUE THREAD

**Issue by dzdnconfuzd** [doppl3r/boxel-rebound#46]
Maybe add a "restart" option in the pause menu so that when I am going for best time on a map I don't have to quit to main menu

**Comment by doppl3r** [comment]
The restart button has been safely nested in the top right corner to prevent accidental restarts:

![mute-retry](https://cloud.githubusercontent.com/assets/3315776/24661793/32ea6f32-1908-11e7-8d44-22c90fffd28b.png)
